### ISSUE TITLE
Support raw background processors

### ISSUE THREAD

**Issue by fatkodima** [Shopify/job-iteration#230]
This is an attempt to add more visibility to https://github.com/Shopify/job-iteration/issues/43, because I haven't receive any response there.

This gem implements a very useful pattern, but assumes that everyone uses `active_job`. But this is not the case due to its limitations. 
So, what do you think about extending it to allow the use with raw processors like `sidekiq` via some kind of adapters? I do not want to reimplement this gem's functionality as a separate gem to allow the use with `sidekiq`, so would be nice if this will be supported natively. I can work on a PR, but are you interested in such changes?

**Comment by fatkodima** [comment]
For anyone interested, I implemented support for raw sidekiq as a separate gem based on this gem - https://github.com/fatkodima/sidekiq-iteration.

cc @schonert

**Comment by Shankar1598** [comment]
Would be great to get native support for this since Sidekiq officially recomments using raw workers instead of ActiveJob to avoid the processing overhead. 😄 
https://github.com/sidekiq/sidekiq/wiki/Active-Job#performance

**Comment by Mangara** [comment]
Sorry, but no. This gem is specifically for Active Job. If you want the same functionality for raw Sidekiq, feel free to fork it or use the linked fork.
